### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by johackim** [ALinuxNinja/docker-postal#3]
Hello,

A bug appear after run `docker-compose up -d` :

```
cp: cannot stat '/opt/postal/config-original/*': No such file or directory
/usr/local/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - /opt/postal/config/postal.defaults.yml (Errno::ENOENT)
        from /usr/local/lib/ruby/2.4.0/psych.rb:472:in `open'
        from /usr/local/lib/ruby/2.4.0/psych.rb:472:in `load_file'
        from /opt/postal/lib/postal/config.rb:59:in `defaults'
        from /opt/postal/lib/postal/config.rb:29:in `config'
        from /opt/postal/lib/postal/config.rb:132:in `fast_server_default_private_key_path'
        from script/generate_initial_config.rb:30:in `<main>'
== Waiting for MySQL to start up ==
/usr/local/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - /opt/postal/config/postal.defaults.yml (Errno::ENOENT)
        from /usr/local/lib/ruby/2.4.0/psych.rb:472:in `open'
        from /usr/local/lib/ruby/2.4.0/psych.rb:472:in `load_file'
        from /opt/postal/lib/postal/config.rb:59:in `defaults'
        from /opt/postal/lib/postal/config.rb:29:in `config'
        from script/update_process_concurrency.rb:4:in `<main>'
```

**Comment by eveandcats** [comment]
Hi,

Thanks for the report.

Can you post the output of the following command please?
```
docker-compose build --no-cache
```

Thanks!

**Comment by johackim** [comment]
@ALinuxNinja Here the output of your command : http://sprunge.us/AdDB
Everything seems ok. I specify that the error appears just for postal container, mysql and rabbitmq run normally.

Thanks!

**Comment by eveandcats** [comment]
Hi @stoneo, can you try again with the new docker-compose.yml.

Seems that the config folder is not being moved properly, I've verified that the automatic builds are working. Please ensure that you do a new git clone.

Thanks!

**Comment by johackim** [comment]
@ALinuxNinja  Thank you very much it works !

**Comment by eveandcats** [comment]
Excellent, glad to see it works now.
